// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/c17b1b78b886e84afe27e1b65fe5bf901da5bbe7/requirejs-domready/index.d.ts
declare module 'requirejs-domready' {
// Type definitions for domReady 2.0.1
// Project: https://github.com/requirejs/domReady
// Definitions by: Nobuhiro Nakamura <https://github.com/lefb766>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


interface DomReady {
    (callback: () => any): DomReady;
    version: string;
}

var domReady: DomReady;

export = domReady;
}
